name: Build (Windows)

permissions:
  contents: read

on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1
        with:
          vulkan_version: latest
          cache: true
      - name: Install MinGW
        run: choco install mingw
      - name: Configure
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Release -DLE_BUILD_TESTS=OFF
      - name: Build
        run: |
          cmake --build build