name: Build (Windows)

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Configure
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DLE_HEADLESS=ON
      - name: Build
        run: |
          cmake --build build --target LegendEngine